/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as ImportIndexImport } from './routes/import/index'
import { Route as IntelligenceIndexImport } from './routes/intelligence/index'
import { Route as RoadmapIndexImport } from './routes/roadmap/index'
import { Route as PrioritiesPriorityIdImport } from './routes/priorities/$priorityId'
import { Route as PrioritiesIndexImport } from './routes/priorities/index'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PrioritiesIndexRoute = PrioritiesIndexImport.update({
  id: '/priorities/',
  path: '/priorities/',
  getParentRoute: () => rootRoute,
} as any)

const PrioritiesPriorityIdRoute = PrioritiesPriorityIdImport.update({
  id: '/priorities/$priorityId',
  path: '/priorities/$priorityId',
  getParentRoute: () => rootRoute,
} as any)

const RoadmapIndexRoute = RoadmapIndexImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRoute,
} as any)

const IntelligenceIndexRoute = IntelligenceIndexImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => rootRoute,
} as any)

const ImportIndexRoute = ImportIndexImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/priorities/': {
      id: '/priorities/'
      path: '/priorities/'
      fullPath: '/priorities/'
      preLoaderRoute: typeof PrioritiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/priorities/$priorityId': {
      id: '/priorities/$priorityId'
      path: '/priorities/$priorityId'
      fullPath: '/priorities/$priorityId'
      preLoaderRoute: typeof PrioritiesPriorityIdImport
      parentRoute: typeof rootRoute
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap/'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexImport
      parentRoute: typeof rootRoute
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/intelligence/'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexImport
      parentRoute: typeof rootRoute
    }
    '/import/': {
      id: '/import/'
      path: '/import/'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PrioritiesIndexRoute,
  PrioritiesPriorityIdRoute,
  RoadmapIndexRoute,
  IntelligenceIndexRoute,
  ImportIndexRoute,
  SettingsIndexRoute,
})

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/priorities/",
        "/priorities/$priorityId",
        "/roadmap/",
        "/intelligence/",
        "/import/",
        "/settings/"
      ]
    },
    "/": { "filePath": "index.tsx" },
    "/priorities/": { "filePath": "priorities/index.tsx" },
    "/priorities/$priorityId": { "filePath": "priorities/$priorityId.tsx" },
    "/roadmap/": { "filePath": "roadmap/index.tsx" },
    "/intelligence/": { "filePath": "intelligence/index.tsx" },
    "/import/": { "filePath": "import/index.tsx" },
    "/settings/": { "filePath": "settings/index.tsx" }
  }
}
ROUTE_MANIFEST_END */
