/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap/index'
import { Route as PrioritiesIndexRouteImport } from './routes/priorities/index'
import { Route as IntelligenceIndexRouteImport } from './routes/intelligence/index'
import { Route as ImportIndexRouteImport } from './routes/import/index'
import { Route as PrioritiesPriorityIdRouteImport } from './routes/priorities/$priorityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesIndexRoute = PrioritiesIndexRouteImport.update({
  id: '/priorities/',
  path: '/priorities/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIndexRoute = IntelligenceIndexRouteImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesPriorityIdRoute = PrioritiesPriorityIdRouteImport.update({
  id: '/priorities/$priorityId',
  path: '/priorities/$priorityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/priorities/$priorityId': typeof PrioritiesPriorityIdRoute
  '/import/': typeof ImportIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/priorities/': typeof PrioritiesIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/priorities/$priorityId': typeof PrioritiesPriorityIdRoute
  '/import': typeof ImportIndexRoute
  '/intelligence': typeof IntelligenceIndexRoute
  '/priorities': typeof PrioritiesIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/priorities/$priorityId': typeof PrioritiesPriorityIdRoute
  '/import/': typeof ImportIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/priorities/': typeof PrioritiesIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/priorities/$priorityId'
    | '/import/'
    | '/intelligence/'
    | '/priorities/'
    | '/roadmap/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/priorities/$priorityId'
    | '/import'
    | '/intelligence'
    | '/priorities'
    | '/roadmap'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/priorities/$priorityId'
    | '/import/'
    | '/intelligence/'
    | '/priorities/'
    | '/roadmap/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrioritiesPriorityIdRoute: typeof PrioritiesPriorityIdRoute
  ImportIndexRoute: typeof ImportIndexRoute
  IntelligenceIndexRoute: typeof IntelligenceIndexRoute
  PrioritiesIndexRoute: typeof PrioritiesIndexRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities/': {
      id: '/priorities/'
      path: '/priorities'
      fullPath: '/priorities/'
      preLoaderRoute: typeof PrioritiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities/$priorityId': {
      id: '/priorities/$priorityId'
      path: '/priorities/$priorityId'
      fullPath: '/priorities/$priorityId'
      preLoaderRoute: typeof PrioritiesPriorityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrioritiesPriorityIdRoute: PrioritiesPriorityIdRoute,
  ImportIndexRoute: ImportIndexRoute,
  IntelligenceIndexRoute: IntelligenceIndexRoute,
  PrioritiesIndexRoute: PrioritiesIndexRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
